title: Organizational change management software | OrgMapper
email: your-email@domain.com
description: >-
  Organizational change management software which helps companies to identify
  the hidden influencers in their organizations who boost internal communication
  and help accelerate change
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
