title: Organizational change management tool | OrgMapper®
email: info@orgmapper.com
description: >-
  Organizational change management software which helps companies to identify
  the hidden influencers in their organizations who boost internal communication
  and help accelerate change
baseurl: ''
url: ''
twitter_username: orgmapper
github_username: orgmapper
markdown: kramdown
sass:
  style: compressed
theme: minima
gems:
  - jekyll-feed
  - algoliasearch-jekyll
exclude:
  - Gemfile
  - Gemfile.lock
google_analytics: UA-100619009-1